# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roberts', '0002_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=130)),
                ('descripcion', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roberts.SubCategoria')),
            ],
            options={
                'verbose_name_plural': 'Contenidos',
            },
        ),
    ]
