# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roberts', '0003_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'verbose_name_plural': 'contenidos'},
        ),
    ]
